### ISSUE TITLE
Songs won't play until the end

### ISSUE THREAD

**Issue by lmlask** [kodi-community-addons/repository.marcelveldt#11]
Repo installs, opens, connects via Spotify Connect as active device just fine. Most songs, however, don't play until the end; they stop in the middle, cough up a bit,sometimes try to continue, but don't. The add-on does load and play the next song when that happens, but Kodi locks up for a while trying to retrieve the data that for some reason it can't get.

**Comment by Angelinas1** [comment]
This isue is for Spotify , not for repo.

**Comment by lmlask** [comment]
Are you sure? My Spotify works perfectly when in other devices

**Comment by Angelinas1** [comment]
This is issue for repo script, you need to write in part for  Spotify script
https://github.com/kodi-community-addons/plugin.audio.spotify/issues
