### ISSUE TITLE
Skin Helper Service error on latest update

### ISSUE THREAD

**Issue by xyzfre** [kodi-community-addons/repository.marcelveldt#12]
The current update of Skin Helper Service is causing a error on my end I'm using AuraMod latest Repo version 1.0.32 ,K19.1 ,Nvidia Shield appreciate any feedback and thank you for all your hard work✊🏼￼ ![image](https://user-images.githubusercontent.com/49699869/122643760-a3d71b80-d0df-11eb-886d-9c3b31bbc637.jpeg)

**Comment by xyzfre** [comment]
I did notice after the last update the dependency script.module.cherrypy became orphaned,, does that mean we can delete it from our system not sure if that's causing the error,, I'm just a end user￼￼￼￼,, just taking a guess￼

**Comment by Angelinas1** [comment]
tnx...for notice webservice.....
for script.module.cherrypy Yes you can remove...
I didn't fix webservice for Matrix...with your fix, webservice is history.

**Comment by xyzfre** [comment]
Sorry to reopen this issue but after deleting script.module.cherrypy I still get the same error in the picture above is there a fix for this appreciate any info￼

**Comment by Angelinas1** [comment]
bump version on Marcel repo .
Please use version 1.1.39

**Comment by xyzfre** [comment]
Thank you for fixing the error ,and thank you for all the hard work that goes into marcelveldt Repo ,, lots of respect ✊🏼
