### ISSUE TITLE
Doesn't work on Kodi 19.2 for Android

### ISSUE THREAD

**Issue by Viper67857** [kodi-community-addons/repository.marcelveldt#15]
Issue relates to multiprocessing library being added to 19.2, as reported by mrezchil on the xbmc github:

[https://github.com/xbmc/xbmc/issues/20276](https://github.com/xbmc/xbmc/issues/20276)

As a workaround, the following code can be added to script.module.metadatautils/lib/helpers/utils.py:

```
if xbmc.getCondVisibility('system.platform.android'):
    SUPPORTS_POOL = False
```

Placed beneath this existing section:

```
try:
    from multiprocessing.pool import ThreadPool
    SUPPORTS_POOL = True
except Exception:
    SUPPORTS_POOL = False
```

**Comment by Olivier-Prince** [comment]
In addition, this [workaround from PKC](https://github.com/croneter/PlexKodiConnect/pull/1644/files) works well too 👍 
Tested on [Kodi 19.3 - Android TV 9.0 - skin RAPIER] to solve a `script.skin.helper.widgets` issue
